name: Deploy and Run Streamlit App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Streamlit App
        run: streamlit run app.py & # To prevent github action to run infinetly added &
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
